# Лабораторная работа №7

Нарматова Бегимай AIN-2-21

1)	Изучите материал лекции 12, проделайте пример, описанный в ходе работы.

In [1]:
from sklearn.datasets import load_files
reviews_train = load_files("aclImdb/train/")

text_train, y_train = reviews_train.data, reviews_train.target
print(type(text_train))
print(len(text_train))
text_train[1]

<class 'list'>
18093


b"this film is really bad....... no i mean really really bad. Tony Scott is a terrible director. out of all the films he has made i only like enemy of the state, besides that he is one of the worse directors of all time. what appalled me the most is Richard Kelly (director of Donnie Darko) did the screenplay to this. now Richard Kelly is a genius in my eyes but to be involved in this makes hope he has learnt his lesson.<br /><br />now i love Mickey Rourke's new roles but i cant even like him in this because of the terrible story and look of it. don't get me wrong i still love Mickey Rourke but he has made a few accidence's in his time and this is one of them. i don't know what to say about Keira knightly, i think she's a little too overrated. i just cant feel for her in films.<br /><br />all in all this film is bad. thats it....... 1/10.......j.d Seaton"

In [2]:
text_train = [doc.replace(b"<br />", b" ") for doc in text_train]
text_train[1]

b"this film is really bad....... no i mean really really bad. Tony Scott is a terrible director. out of all the films he has made i only like enemy of the state, besides that he is one of the worse directors of all time. what appalled me the most is Richard Kelly (director of Donnie Darko) did the screenplay to this. now Richard Kelly is a genius in my eyes but to be involved in this makes hope he has learnt his lesson.  now i love Mickey Rourke's new roles but i cant even like him in this because of the terrible story and look of it. don't get me wrong i still love Mickey Rourke but he has made a few accidence's in his time and this is one of them. i don't know what to say about Keira knightly, i think she's a little too overrated. i just cant feel for her in films.  all in all this film is bad. thats it....... 1/10.......j.d Seaton"

In [3]:
import numpy as np
np.unique(y_train)

array([0, 1])

In [4]:
np.bincount(y_train)

array([12500,  5593], dtype=int64)

In [6]:
reviews_test = load_files("aclImdb/test/")
text_test, y_test = reviews_test.data, reviews_test.target
print(len(text_test))
text_test = [doc.replace(b"<br />", b" ") for doc in text_test]
np.bincount(y_test)

25000


array([12500, 12500], dtype=int64)

2)	Создайте свой «мешок слов», например, набор из 20-25 отзывов о чем-либо, напишите краткое пояснение к данным.

In [77]:
from sklearn.feature_extraction.text import CountVectorizer

# Примеры отзывов 
reviews = [
    "Отличный фильм, понравилось, рекомендую",
    "Сюжет неплохой, но актерская игра не впечатлила",
    "Фильм ужасен, не стоит тратить время",
    "Фильм поразил своей глубиной и сюжетной линией, рекомендую всем",
    "Актерская игра на высшем уровне, сюжет захватывает с первых минут",
    "Безумно скучный фильм, не стоит тратить время на просмотр",
    "Понравилось исполнение ролей, но сюжет оставляет желать лучшего",
    "Отличный фильм, смотрел не отрываясь",
    "Фильм оставил разноречивые впечатления, но в целом понравился",
    "Отличная игра актеров, сюжет вызывает восхищение",
    "Сюжет просто потрясающий, рекомендую к просмотру всем",
    "Полное разочарование, не стоит тратить время на этот фильм",
    "Фильм оказался невероятно интересным и захватывающим",
    "Смотрел в один присест, не мог оторваться",
    "Сюжет заставил задуматься, актеры на высоте",
    "Плоский сюжет и неубедительные диалоги, не впечатлило",
    "Интригующий фильм с неожиданным развитием событий",
    "Отличный сюжет, монтаж и сценарий на высоте",
    "Отличная режиссура и игра актеров, но сюжет немного предсказуем",
    "Фильм никак не зацепил, скучно и невыразительно",
    "Сюжет вызывает вопросы, но в целом интересный фильм",
    "Интересный сюжет, хотя и были моменты неубедительные",
    "Сюжет непредсказуемый, но иногда теряется логика",
    "Фильм оставил горьковатый привкус, не раскрыты некоторые моменты",
    "Сильная игра актеров, но сюжет оказался слабым",  
]

# Инициализация CountVectorizer для создания «мешка слов»
vectorizer = CountVectorizer()

# Создание «мешка слов»
X = vectorizer.fit_transform(reviews)

# Получение списка слов
feature_names = vectorizer.get_feature_names_out()
print("Словарь слов:", feature_names)

# Вывод матрицы признаков
print("Матрица признаков (мешок слов):\n", X.toarray())


Словарь слов: ['актеров' 'актерская' 'актеры' 'безумно' 'были' 'вопросы' 'восхищение'
 'впечатления' 'впечатлила' 'впечатлило' 'время' 'всем' 'вызывает'
 'высоте' 'высшем' 'глубиной' 'горьковатый' 'диалоги' 'желать'
 'задуматься' 'заставил' 'захватывает' 'захватывающим' 'зацепил' 'игра'
 'иногда' 'интересный' 'интересным' 'интригующий' 'исполнение' 'линией'
 'логика' 'лучшего' 'минут' 'мог' 'моменты' 'монтаж' 'на' 'не'
 'невероятно' 'невыразительно' 'некоторые' 'немного' 'неожиданным'
 'неплохой' 'непредсказуемый' 'неубедительные' 'никак' 'но' 'один'
 'оказался' 'оставил' 'оставляет' 'отличная' 'отличный' 'оторваться'
 'отрываясь' 'первых' 'плоский' 'полное' 'понравилось' 'понравился'
 'поразил' 'потрясающий' 'предсказуем' 'привкус' 'присест' 'просмотр'
 'просмотру' 'просто' 'развитием' 'разноречивые' 'разочарование'
 'раскрыты' 'режиссура' 'рекомендую' 'ролей' 'своей' 'сильная' 'скучно'
 'скучный' 'слабым' 'смотрел' 'событий' 'стоит' 'сценарий' 'сюжет'
 'сюжетной' 'теряется' 'тратить'

3)	Создайте словарь стоп-слов, примените стоп-слова к своему «мешку слов»

In [78]:
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [79]:
from nltk.corpus import stopwords

# Загрузка списка стоп-слов 
stop_words = set(stopwords.words('russian'))

# Применение стоп-слов к вашему «мешку слов»
vectorizer = CountVectorizer(stop_words=list(stopwords.words('russian')))
X = vectorizer.fit_transform(reviews)

# Получение списка слов после применения стоп-слов
feature_names = vectorizer.get_feature_names_out()
print("Словарь слов после удаления стоп-слов:", feature_names)


Словарь слов после удаления стоп-слов: ['актеров' 'актерская' 'актеры' 'безумно' 'вопросы' 'восхищение'
 'впечатления' 'впечатлила' 'впечатлило' 'время' 'всем' 'вызывает'
 'высоте' 'высшем' 'глубиной' 'горьковатый' 'диалоги' 'желать'
 'задуматься' 'заставил' 'захватывает' 'захватывающим' 'зацепил' 'игра'
 'интересный' 'интересным' 'интригующий' 'исполнение' 'линией' 'логика'
 'лучшего' 'минут' 'мог' 'моменты' 'монтаж' 'невероятно' 'невыразительно'
 'некоторые' 'немного' 'неожиданным' 'неплохой' 'непредсказуемый'
 'неубедительные' 'никак' 'оказался' 'оставил' 'оставляет' 'отличная'
 'отличный' 'оторваться' 'отрываясь' 'первых' 'плоский' 'полное'
 'понравилось' 'понравился' 'поразил' 'потрясающий' 'предсказуем'
 'привкус' 'присест' 'просмотр' 'просмотру' 'просто' 'развитием'
 'разноречивые' 'разочарование' 'раскрыты' 'режиссура' 'рекомендую'
 'ролей' 'своей' 'сильная' 'скучно' 'скучный' 'слабым' 'смотрел' 'событий'
 'стоит' 'сценарий' 'сюжет' 'сюжетной' 'теряется' 'тратить' 'ужасен'
 'ур

4)	Масштабируйте данные с помощью tf-idf

In [80]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Создание объекта TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words=list(stopwords.words('russian')))

# Преобразование текстовых данных в матрицу TF-IDF признаков
X_tfidf = tfidf_vectorizer.fit_transform(reviews)

# Вывод TF-IDF признаков
print("TF-IDF признаки:\n", X_tfidf.toarray())


TF-IDF признаки:
 [[0.         0.         0.         ... 0.31256341 0.         0.        ]
 [0.         0.47574731 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.26665437 0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.19726887 0.         0.        ]
 [0.39690839 0.         0.         ... 0.         0.         0.        ]]


5)	Исследуйте коэффициенты модели

In [85]:
from sklearn.linear_model import LinearRegression
from sklearn.feature_extraction.text import TfidfVectorizer
# Оценка фильмов
y_train = [4.5, 2.0, 3.5, 5.0, 3.0, 4.0, 2.5, 4.0, 3.0, 5.0, 
           4.5, 3.0, 2.0, 4.0, 3.5, 4.0, 3.0, 2.5, 4.0, 3.5, 
           4.0, 2.0, 3.0, 4.5, 3.5]

# Создание модели линейной регрессии
model = LinearRegression()

# Обучение модели на TF-IDF данных
model.fit(X_tfidf, y_train)

# Получение предсказаний на тренировочных данных (X_tfidf)
predictions = model.predict(X_tfidf)

# Получение коэффициентов модели (весов слов)
coefficients = model.coef_

# Вывод коэффициентов и предсказаний
print("Коэффициенты модели:", coefficients)
print("Предсказания на тренировочных данных:", predictions)


Коэффициенты модели: [ 0.8589942  -0.85443174  0.26160968  0.44203539 -0.98024609  0.56551725
  0.74627959 -0.38299138 -0.93666643  0.50585551 -0.04198328  0.65233296
  1.16259757 -0.39165981 -0.02741683  0.45424639  0.60244226  0.50585551
 -0.43065247  0.26160968  0.26160968 -0.02741683 -0.85523434 -0.05169371
  0.07073297 -0.11394331 -0.36755901 -0.85523434 -0.27606965 -0.43065247
  0.45424639 -0.11394331 -0.43065247 -0.02741683  0.21100651 -0.33483372
 -0.70353224 -0.27568259  0.24633755 -0.85523434 -0.05169371  0.60244226
  0.12484966 -0.27606965 -0.93666643 -0.11394331 -0.42043503 -0.05169371
 -0.59811023  0.21100651 -0.58496919  0.19449129 -0.43065247  0.77205
  0.19442791  0.21100651  0.17025226 -0.02741683  0.50585551 -0.37117943
  0.30485969 -0.38299138  0.45424639  0.28180222  0.12484966  0.60244226
  0.21100651  0.44203539  0.28180222  0.28180222 -0.27606965 -0.38299138
 -0.37117943  0.60244226  0.12484966  1.21695593 -0.43065247  0.45424639
  0.19519448 -0.05169371  0.44203

6)	Сделайте выводы по работе.

В ходе работы была выполнена обработка текстовых данных с использованием метода TF-IDF (Term Frequency-Inverse Document Frequency). Этот метод позволяет преобразовать тексты в числовые признаки, учитывая важность слов в документе и в корпусе текстов в целом.

Сначала были подготовлены отзывы (reviews) и преобразованы с помощью TF-IDF векторизатора, что позволило представить текстовые данные в виде числовой матрицы.

Далее была использована линейная регрессия для обучения модели на этих TF-IDF данных и массиве оценок фильмов (y_train). Однако, стоит отметить, что модель была обучена на тех же данных, на которых она делает предсказания, что не является правильным подходом для оценки реальной производительности модели. В реальности, необходимо разделить данные на тренировочный и тестовый наборы для корректной проверки модели.

Также, можно дополнительно исследовать коэффициенты модели (веса слов), чтобы понять, какие слова сильнее всего влияют на предсказания модели.

В целом, для улучшения работы необходимо провести более подробный анализ, корректно разделить данные на тренировочный и тестовый наборы, подобрать оптимальные параметры модели и выполнить ее оценку на тестовых данных.